version: "3.8"
services:
  api_service:
    build: 
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc: mysql://mysqldb:3306/libreria?createDatabaseIfNotExist=true 
      - spring.datasource.username: leonel
      - spring.datasource.password: 1234
    depends_on:
        mysqldb:
           condition: service_healthy
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: libreria
      MYSQL_USER: leonel
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
networks:
  springapimysql-net: