version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABdocdockASE: libreria
      MYSQL_USER: leonel
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      
  api_service:
    build: 
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:     
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/libreria?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: leonel
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DB: libreria
    depends_on:
        mysqldb:
           condition: service_healthy
networks:
  springapimysql-net: